export type TemplateRouteKind =
  | 'overview'
  | 'table'
  | 'cards'
  | 'form'
  | 'settings'
  | 'profile'
  | 'colors'
  | 'resultSuccess'
  | 'resultFail'
  | 'utility'
  | 'guard'
  | 'download';

export interface TemplateDemoRoute {
  path: string;
  title: string;
  group: string;
  originalModule: string;
  kind: TemplateRouteKind;
  description: string;
  redirectTo?: string;
}

// Keeps original NG-Alain demo/template routes reachable in the React copy.
export const templateDemoRoutes: TemplateDemoRoute[] = [
  {
    path: '/widgets',
    title: 'Widgets',
    group: '组件示例',
    originalModule: 'WidgetsModule',
    kind: 'overview',
    description: '原系统 Widgets 模块入口。',
  },
  {
    path: '/widgets/datatable',
    title: 'Datatable',
    group: '组件示例',
    originalModule: 'WidgetsModule',
    kind: 'table',
    description: '原系统数据表格示例。',
  },
  {
    path: '/demo/datatable',
    title: 'Datatable',
    group: '组件示例',
    originalModule: 'DemoModule',
    kind: 'table',
    description: '原系统 DemoModule 数据表格示例。',
  },
  {
    path: '/style',
    title: 'Style',
    group: '样式示例',
    originalModule: 'StyleModule',
    kind: 'overview',
    description: '原系统样式模块入口。',
  },
  {
    path: '/style/gridmasonry',
    title: 'Grid Masonry',
    group: '样式示例',
    originalModule: 'StyleModule',
    kind: 'cards',
    description: '原系统瀑布流布局示例。',
  },
  {
    path: '/style/typography',
    title: 'Typography',
    group: '样式示例',
    originalModule: 'StyleModule',
    kind: 'utility',
    description: '原系统排版示例。',
  },
  {
    path: '/style/colors',
    title: 'Colors',
    group: '样式示例',
    originalModule: 'StyleModule',
    kind: 'colors',
    description: '原系统颜色示例。',
  },
  {
    path: '/extras',
    title: 'Extras',
    group: '扩展页',
    originalModule: 'ExtrasModule',
    kind: 'overview',
    description: '原系统扩展页面入口。',
  },
  {
    path: '/extras/helpcenter',
    title: 'Help Center',
    group: '扩展页',
    originalModule: 'ExtrasModule',
    kind: 'cards',
    description: '原系统帮助中心示例。',
  },
  {
    path: '/extras/settings',
    title: 'Personal Settings',
    group: '扩展页',
    originalModule: 'ExtrasModule',
    kind: 'settings',
    description: '原系统个人设置示例。',
  },
  {
    path: '/extras/poi',
    title: 'POI',
    group: '扩展页',
    originalModule: 'ExtrasModule',
    kind: 'table',
    description: '原系统门店列表示例。',
  },
  {
    path: '/pro',
    title: 'Pro',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'overview',
    description: '原系统 Pro 模板入口。',
  },
  {
    path: '/pro/form',
    title: 'Form',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'form',
    description: '原系统表单模板入口。',
  },
  {
    path: '/pro/form/basic-form',
    title: 'Basic Form',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'form',
    description: '原系统基础表单模板。',
  },
  {
    path: '/pro/form/step-form',
    title: 'Step Form',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'form',
    description: '原系统分步表单模板。',
  },
  {
    path: '/pro/form/advanced-form',
    title: 'Advanced Form',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'form',
    description: '原系统高级表单模板。',
  },
  {
    path: '/pro/list',
    title: 'List',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'table',
    description: '原系统列表模板入口。',
  },
  {
    path: '/pro/list/table-list',
    title: 'Table List',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'table',
    description: '原系统查询表格模板。',
  },
  {
    path: '/pro/list/basic-list',
    title: 'Basic List',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'table',
    description: '原系统标准列表模板。',
  },
  {
    path: '/pro/list/card-list',
    title: 'Card List',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'cards',
    description: '原系统卡片列表模板。',
  },
  {
    path: '/pro/list/articles',
    title: 'Articles',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'table',
    description: '原系统文章列表模板。',
  },
  {
    path: '/pro/list/projects',
    title: 'Projects',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'cards',
    description: '原系统项目列表模板。',
  },
  {
    path: '/pro/list/applications',
    title: 'Applications',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'cards',
    description: '原系统应用列表模板。',
  },
  {
    path: '/pro/profile',
    title: 'Profile',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'profile',
    description: '原系统详情页模板入口。',
  },
  {
    path: '/pro/profile/basic',
    title: 'Basic Profile',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'profile',
    description: '原系统基础详情页模板。',
  },
  {
    path: '/pro/profile/advanced',
    title: 'Advanced Profile',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'profile',
    description: '原系统高级详情页模板。',
  },
  {
    path: '/pro/result',
    title: 'Result',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'overview',
    description: '原系统结果页模板入口。',
  },
  {
    path: '/pro/result/success',
    title: 'Success',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'resultSuccess',
    description: '原系统成功结果页模板。',
  },
  {
    path: '/pro/result/fail',
    title: 'Fail',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'resultFail',
    description: '原系统失败结果页模板。',
  },
  {
    path: '/pro/account',
    title: 'Account',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'overview',
    description: '原系统账户模板入口。',
  },
  {
    path: '/pro/account/center',
    title: 'Account Center',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'profile',
    description: '原系统账户中心模板。',
    redirectTo: '/pro/account/center/articles',
  },
  {
    path: '/pro/account/center/articles',
    title: 'Account Articles',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'table',
    description: '原系统账户文章列表模板。',
  },
  {
    path: '/pro/account/center/projects',
    title: 'Account Projects',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'cards',
    description: '原系统账户项目列表模板。',
  },
  {
    path: '/pro/account/center/applications',
    title: 'Account Applications',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'cards',
    description: '原系统账户应用列表模板。',
  },
  {
    path: '/pro/account/settings',
    title: 'Account Settings',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'settings',
    description: '原系统账户设置模板。',
    redirectTo: '/pro/account/settings/base',
  },
  {
    path: '/pro/account/settings/base',
    title: 'Basic Settings',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'settings',
    description: '原系统基本设置模板。',
  },
  {
    path: '/pro/account/settings/security',
    title: 'Security Settings',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'settings',
    description: '原系统安全设置模板。',
  },
  {
    path: '/pro/account/settings/binding',
    title: 'Account Binding',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'settings',
    description: '原系统账号绑定模板。',
  },
  {
    path: '/pro/account/settings/notification',
    title: 'Notification Settings',
    group: 'Pro 模板',
    originalModule: 'ProModule',
    kind: 'settings',
    description: '原系统通知设置模板。',
  },
  {
    path: '/delon',
    title: 'DELON',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'overview',
    description: '原系统 DELON 组件入口。',
  },
  {
    path: '/delon/st',
    title: 'ST',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'table',
    description: '原系统 ST 表格组件示例。',
  },
  {
    path: '/delon/util',
    title: 'Util',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'utility',
    description: '原系统工具函数示例。',
  },
  {
    path: '/delon/print',
    title: 'Print',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'utility',
    description: '原系统 Lodop 打印示例。',
  },
  {
    path: '/delon/acl',
    title: 'ACL',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'guard',
    description: '原系统 ACL 权限示例。',
  },
  {
    path: '/delon/guard',
    title: 'Route Guard',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'guard',
    description: '原系统路由守卫示例。',
  },
  {
    path: '/delon/guard/leave',
    title: 'Leave Guard',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'guard',
    description: '原系统离开确认守卫示例。',
  },
  {
    path: '/delon/guard/auth',
    title: 'Auth Guard',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'guard',
    description: '原系统认证守卫示例。',
  },
  {
    path: '/delon/guard/admin',
    title: 'Admin Guard',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'guard',
    description: '原系统管理员守卫示例。',
  },
  {
    path: '/delon/auth',
    title: 'Auth',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'utility',
    description: '原系统认证工具示例。',
  },
  {
    path: '/delon/admin',
    title: 'Admin',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'utility',
    description: '原系统管理工具示例。',
  },
  {
    path: '/delon/cache',
    title: 'Cache',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'utility',
    description: '原系统缓存组件示例。',
  },
  {
    path: '/delon/qr',
    title: 'QR',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'utility',
    description: '原系统二维码组件示例。',
  },
  {
    path: '/delon/downfile',
    title: 'Downfile',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'download',
    description: '原系统文件下载组件示例。',
  },
  {
    path: '/delon/xlsx',
    title: 'XLSX',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'download',
    description: '原系统 Excel 组件示例。',
  },
  {
    path: '/delon/zip',
    title: 'ZIP',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'download',
    description: '原系统 ZIP 组件示例。',
  },
  {
    path: '/delon/demo.docx',
    title: 'Demo Docx',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'download',
    description: '原系统 Word 下载示例。',
  },
  {
    path: '/delon/小程序标志.zip',
    title: '小程序标志 ZIP',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'download',
    description: '原系统中文文件名下载示例。',
  },
  {
    path: '/delon/form',
    title: 'SF Form',
    group: 'DELON 组件',
    originalModule: 'DelonModule',
    kind: 'form',
    description: '原系统动态表单组件示例。',
  },
];
